/**
 * generate-sprites.js — creates Focus Town pixel art sprite sheets
 * Pure Node.js, zero npm deps (uses built-in zlib + fs).
 * Run: node scripts/generate-sprites.js
 *
 * Output:
 *   public/assets/focus-town/characters/worker-blue.png   (32×16: 2 anim frames)
 *   public/assets/focus-town/characters/worker-amber.png
 *   public/assets/focus-town/characters/worker-teal.png
 *   public/assets/focus-town/environment/desk.png          (16×16)
 *   public/assets/focus-town/environment/plant.png
 *   public/assets/focus-town/environment/bookshelf.png
 *   public/assets/focus-town/environment/floor.png
 *
 * License: generated by this project, CC0.
 */

import { deflateSync } from 'zlib';
import { writeFileSync, mkdirSync } from 'fs';
import { fileURLToPath } from 'url';
import path from 'path';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');
const OUT_CHARS = path.join(ROOT, 'public/assets/focus-town/characters');
const OUT_ENV   = path.join(ROOT, 'public/assets/focus-town/environment');
mkdirSync(OUT_CHARS, { recursive: true });
mkdirSync(OUT_ENV,   { recursive: true });

// ── PNG encoder (pure Node, no deps) ────────────────────────────────────────

function crc32(buf) {
  let c = 0xFFFFFFFF;
  for (const b of buf) {
    c ^= b;
    for (let i = 0; i < 8; i++) c = (c & 1) ? (0xEDB88320 ^ (c >>> 1)) : (c >>> 1);
  }
  return (c ^ 0xFFFFFFFF) >>> 0;
}

function pngChunk(type, data) {
  const t = Buffer.from(type, 'ascii');
  const d = Buffer.isBuffer(data) ? data : Buffer.from(data);
  const len = Buffer.alloc(4); len.writeUInt32BE(d.length);
  const crcBuf = Buffer.alloc(4); crcBuf.writeUInt32BE(crc32(Buffer.concat([t, d])));
  return Buffer.concat([len, t, d, crcBuf]);
}

/** pixels: Uint8Array of RGBA bytes, row-major */
function encodePNG(width, height, pixels) {
  const ihdr = Buffer.alloc(13);
  ihdr.writeUInt32BE(width, 0); ihdr.writeUInt32BE(height, 4);
  ihdr[8] = 8; ihdr[9] = 6; // 8-bit RGBA

  // Filter byte 0 (None) before each row
  const raw = Buffer.alloc(height * (1 + width * 4));
  for (let y = 0; y < height; y++) {
    raw[y * (1 + width * 4)] = 0;
    for (let x = 0; x < width; x++) {
      const si = (y * width + x) * 4;
      const di = y * (1 + width * 4) + 1 + x * 4;
      raw[di]     = pixels[si];
      raw[di + 1] = pixels[si + 1];
      raw[di + 2] = pixels[si + 2];
      raw[di + 3] = pixels[si + 3];
    }
  }

  return Buffer.concat([
    Buffer.from([137, 80, 78, 71, 13, 10, 26, 10]), // PNG sig
    pngChunk('IHDR', ihdr),
    pngChunk('IDAT', deflateSync(raw)),
    pngChunk('IEND', Buffer.alloc(0)),
  ]);
}

// ── Pixel canvas helpers ─────────────────────────────────────────────────────

function canvas(w, h) {
  const px = new Uint8Array(w * h * 4); // all transparent
  const set = (x, y, r, g, b, a = 255) => {
    if (x < 0 || x >= w || y < 0 || y >= h) return;
    const i = (y * w + x) * 4;
    px[i] = r; px[i+1] = g; px[i+2] = b; px[i+3] = a;
  };
  const fill = (x1, y1, x2, y2, r, g, b, a = 255) => {
    for (let y = y1; y <= y2; y++) for (let x = x1; x <= x2; x++) set(x, y, r, g, b, a);
  };
  const save = (outPath) => writeFileSync(outPath, encodePNG(w, h, px));
  return { px, set, fill, save };
}

// ── Color palette ─────────────────────────────────────────────────────────────
// Named RGBA tuples. Values spread into set/fill as (r,g,b,a).

const C = {
  // skin/face
  SKIN:   [240, 195, 155],
  SKIN2:  [225, 178, 132],
  EYE:    [45,  45,  55],
  MOUTH:  [180, 110,  90],
  HAIR_BR:[100,  65,  40],   // brown hair
  HAIR_BK:[30,   25,  25],   // black hair
  HAIR_AU:[200, 130,  60],   // auburn
  // shirts (per variant)
  BLUE:   [59,  130, 246],
  BLUE_D: [37,   99, 235],
  AMBER:  [245, 158,  11],
  AMBER_D:[180, 110,   5],
  TEAL:   [20,  184, 166],
  TEAL_D: [13,  148, 136],
  // pants
  PANTS:  [55,  65,  81],
  PANTS_D:[40,  48,  60],
  // chair
  CHAIR:  [120, 113, 108],
  CHAIR_D:[90,   84,  79],
  // env
  DESK_T: [180, 140,  95],   // desk top
  DESK_S: [140, 105,  65],   // desk side
  DESK_L: [120,  90,  55],   // desk leg
  PLANT_G:[34,  197, 110],   // leaf bright
  PLANT_G2:[22, 160,  80],   // leaf dark
  PLANT_P:[140, 100,  65],   // pot
  SHELF_W:[220, 200, 175],   // shelf wood
  SHELF_D:[170, 145, 115],   // shelf dark
  BOOK_R: [220,  60,  60],
  BOOK_B: [60,  100, 220],
  BOOK_Y: [220, 180,  40],
  BOOK_G: [60,  160,  80],
  FLOOR:  [50,   45,  55],   // dark floor tile
  FLOOR_G:[60,   55,  68],   // grout lines
};

// ── Character generator ───────────────────────────────────────────────────────
// Draws a 16×16 top-down seated student. Two animation frames side-by-side
// in a 32×16 spritesheet. Typing animation: arms move slightly between frames.

function drawCharacter(shirtC, shirtD, hairC, frame) {
  // Returns a function that draws onto a canvas at offset ox,oy
  return (cvs, ox, oy) => {
    const { set, fill } = cvs;

    // ── Head (rows 1-5 relative, centered around ox+7,8) ─────────────────
    const hx = ox + 5, hy = oy + 1; // head top-left corner in sprite space
    fill(hx+1, hy,   hx+4, hy,   ...hairC);           // top hair row
    fill(hx,   hy+1, hx,   hy+3, ...hairC);            // left hair
    fill(hx+5, hy+1, hx+5, hy+3, ...hairC);            // right hair
    fill(hx+1, hy+4, hx+4, hy+4, ...hairC);            // bottom hair
    fill(hx+1, hy+1, hx+4, hy+3, ...C.SKIN);           // face
    // eyes
    set(hx+1, hy+2, ...C.EYE);
    set(hx+3, hy+2, ...C.EYE);
    // subtle mouth
    set(hx+2, hy+3, ...C.MOUTH);

    // ── Body / shirt (rows 6-9) ──────────────────────────────────────────
    fill(ox+5, oy+6, ox+9, oy+6, ...shirtC);
    fill(ox+4, oy+7, ox+9, oy+7, ...shirtC);
    fill(ox+4, oy+8, ox+9, oy+8, ...shirtD);
    fill(ox+4, oy+9, ox+9, oy+9, ...shirtD);

    // ── Arms (rows 10-11) — two frames differ here ───────────────────────
    if (frame === 0) {
      // idle: arms resting, slightly inward
      set(ox+3, oy+10, ...shirtC); set(ox+10, oy+10, ...shirtC);
      set(ox+2, oy+11, ...C.SKIN); set(ox+3, oy+11, ...shirtC);
      set(ox+10, oy+11, ...shirtC); set(ox+11, oy+11, ...C.SKIN);
    } else {
      // typing: arms forward (1px closer to desk = up)
      set(ox+3, oy+9,  ...shirtC); set(ox+10, oy+9,  ...shirtC);
      set(ox+2, oy+10, ...C.SKIN); set(ox+3, oy+10, ...shirtC);
      set(ox+10, oy+10, ...shirtC); set(ox+11, oy+10, ...C.SKIN);
    }

    // ── Chair back (visible above seated person, rows 0-1) ──────────────
    fill(ox+5, oy+0, ox+9, oy+0, ...C.CHAIR);
    set(ox+4, oy+0, ...C.CHAIR_D); set(ox+10, oy+0, ...C.CHAIR_D);

    // ── Chair seat (rows 12-14) ──────────────────────────────────────────
    fill(ox+4, oy+12, ox+9, oy+12, ...C.CHAIR_D);
    fill(ox+3, oy+13, ox+10, oy+13, ...C.CHAIR);
    fill(ox+4, oy+14, ox+9, oy+14, ...C.CHAIR_D);
  };
}

// Writes a 32×16 sprite sheet: frame0 at x=0, frame1 at x=16
function makeCharSheet(name, shirtC, shirtD, hairC) {
  const cvs = canvas(32, 16);
  drawCharacter(shirtC, shirtD, hairC, 0)(cvs, 0, 0);  // frame 0: idle
  drawCharacter(shirtC, shirtD, hairC, 1)(cvs, 16, 0); // frame 1: typing
  cvs.save(path.join(OUT_CHARS, `${name}.png`));
  console.log(`  ✓ characters/${name}.png`);
}

// ── Environment tiles (16×16 each) ───────────────────────────────────────────

function makeDesk() {
  const cvs = canvas(16, 16);
  const { fill, set } = cvs;
  // desk top surface
  fill(1, 1, 14, 11, ...C.DESK_T);
  // subtle wood grain lines
  for (let x = 2; x < 14; x += 3) fill(x, 2, x, 10, ...C.DESK_S);
  // desk front edge (dark)
  fill(1, 12, 14, 12, ...C.DESK_S);
  // desk legs
  fill(1, 13, 2, 15, ...C.DESK_L);
  fill(13, 13, 14, 15, ...C.DESK_L);
  // top highlight
  fill(2, 1, 13, 1, 210, 170, 120);
  cvs.save(path.join(OUT_ENV, 'desk.png'));
  console.log('  ✓ environment/desk.png');
}

function makePlant() {
  const cvs = canvas(16, 16);
  const { fill, set } = cvs;
  // pot
  fill(5, 11, 10, 14, ...C.PLANT_P);
  fill(4, 12, 4,  14, ...C.PLANT_P);
  fill(11, 12, 11, 14, ...C.PLANT_P);
  set(5, 15, ...C.PLANT_P); set(10, 15, ...C.PLANT_P);
  // pot highlight
  fill(6, 11, 9, 12, 160, 120, 80);
  // leaves — overlapping circles
  fill(5, 4, 10, 9, ...C.PLANT_G);
  fill(3, 5, 7,  9, ...C.PLANT_G);
  fill(8, 5, 12, 9, ...C.PLANT_G);
  fill(6, 2, 9,  6, ...C.PLANT_G);
  // darker inner shadows
  fill(6, 6, 9, 8, ...C.PLANT_G2);
  fill(5, 7, 7, 9, ...C.PLANT_G2);
  // stem
  fill(7, 9, 8, 11, 80, 50, 30);
  cvs.save(path.join(OUT_ENV, 'plant.png'));
  console.log('  ✓ environment/plant.png');
}

function makeBookshelf() {
  const cvs = canvas(16, 16);
  const { fill, set } = cvs;
  // shelf frame
  fill(0, 0, 15, 15, ...C.SHELF_W);
  // left + right sides darker
  fill(0, 0, 1, 15, ...C.SHELF_D);
  fill(14, 0, 15, 15, ...C.SHELF_D);
  // shelf planks
  fill(2, 7, 13, 8, ...C.SHELF_D);
  fill(2, 0, 13, 0, ...C.SHELF_D);
  // books top shelf
  fill(2, 1, 3, 6, ...C.BOOK_R);
  fill(4, 1, 4, 6, 200, 50, 50);
  fill(5, 1, 6, 6, ...C.BOOK_B);
  fill(7, 2, 7, 6, 50, 80, 200);
  fill(8, 1, 9, 6, ...C.BOOK_Y);
  fill(10, 1, 11, 6, ...C.BOOK_G);
  fill(12, 2, 13, 6, ...C.BOOK_R);
  // books bottom shelf
  fill(2, 9, 4, 14, ...C.BOOK_G);
  fill(5, 9, 6, 14, ...C.BOOK_B);
  fill(7, 10, 8, 14, ...C.BOOK_Y);
  fill(9, 9, 10, 14, 180, 60, 60);
  fill(11, 9, 13, 14, ...C.BOOK_B);
  // book spines (top edge of each book, lighter)
  fill(2, 1, 3, 1, 255, 100, 100);
  fill(5, 1, 6, 1, 100, 130, 255);
  fill(8, 1, 9, 1, 255, 220, 80);
  cvs.save(path.join(OUT_ENV, 'bookshelf.png'));
  console.log('  ✓ environment/bookshelf.png');
}

function makeFloor() {
  const cvs = canvas(16, 16);
  const { fill, set } = cvs;
  // base dark floor
  fill(0, 0, 15, 15, ...C.FLOOR);
  // grout grid lines
  fill(0, 7, 15, 8, ...C.FLOOR_G);
  fill(7, 0, 8, 15, ...C.FLOOR_G);
  // subtle tile sheen (top-left of each quadrant slightly lighter)
  fill(1, 1, 5, 5, 58, 52, 65);
  fill(9, 1, 13, 5, 58, 52, 65);
  fill(1, 9, 5, 13, 58, 52, 65);
  fill(9, 9, 13, 13, 58, 52, 65);
  cvs.save(path.join(OUT_ENV, 'floor.png'));
  console.log('  ✓ environment/floor.png');
}

// ── Generate all assets ───────────────────────────────────────────────────────

console.log('\nGenerating Focus Town sprites...\n');

console.log('Characters:');
makeCharSheet('worker-blue',  C.BLUE,  C.BLUE_D,  C.HAIR_BR);
makeCharSheet('worker-amber', C.AMBER, C.AMBER_D, C.HAIR_BK);
makeCharSheet('worker-teal',  C.TEAL,  C.TEAL_D,  C.HAIR_AU);

console.log('\nEnvironment:');
makeDesk();
makePlant();
makeBookshelf();
makeFloor();

console.log('\nDone. Assets in public/assets/focus-town/\n');
console.log('CSS usage example:');
console.log('  .char { width:16px; height:16px; background:url(/assets/focus-town/characters/worker-blue.png) steps(2) 0 0; }');
console.log('  @keyframes walk { to { background-position: -32px 0; } }');
